<?php

/**
 * @file
 * Contains bubblesort.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bubblesort_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bubblesort module.
    case 'help.page.bubblesort':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function bubblesort_theme($existing, $type, $theme, $path) {
  return [
    'bubblesort_view' => [
      'variables' => [
        'set' => [],
        'pos' => 0,
        'complete' => 0,
      ],
      'template' => 'bubblesort',
    ]
  ];

}
